In [21]:
from io_utils import read_fbin, read_ibin
file_path = "/users/dellatod/yandex/t2l1b/base.1M.fbin"
query_path = "/users/dellatod/yandex/t2l1b/query.public.100K.fbin"
ground_truth_path = "/users/dellatod/yandex/t2l1b/groundtruth.public.100K.ibin"
data_vector = read_fbin(file_path)

In [18]:
print(type(data_vector))
print(data_vector.ndim, data_vector.shape, data_vector.dtype, data_vector.size)
print(data_vector[:3])  # Print first 3 elements to verify content

<class 'numpy.ndarray'>
2 (1000000, 200) float32 200000000
[[-7.01329485e-03  9.25160870e-02  1.00417279e-01 -1.00493655e-02
  -1.47095039e-01 -2.00530775e-02 -6.09966274e-03 -2.37616748e-02
  -7.86866248e-02 -6.40348420e-02  8.38531554e-02  2.76238844e-02
  -6.08940283e-03  4.68223915e-02  1.20988481e-01 -1.37456749e-02
   3.42740342e-02  1.27290934e-02  6.98486716e-03  1.79044232e-02
  -8.84549320e-03  1.45399151e-03  2.13313568e-03 -1.72627121e-02
   5.39611802e-02  5.50855175e-02  2.81234514e-02 -1.02877438e-01
  -1.54077739e-03 -2.69111842e-02  3.34999561e-02  3.58610861e-02
   9.96757895e-02  1.01502664e-01 -3.54767893e-03 -1.11706937e-02
  -6.51973039e-02  2.21656367e-01  5.90528511e-02 -1.01397283e-01
  -1.25850551e-03 -4.51538600e-02  1.04595184e-01 -4.41186391e-02
  -7.30799660e-02 -2.66240910e-02 -7.14782719e-03 -6.32865876e-02
   5.05496562e-02 -4.47978154e-02 -1.03615418e-01  3.33143100e-02
  -8.27219635e-02 -3.53932604e-02 -5.77266552e-02  5.13702258e-02
  -8.69005695e-02

In [19]:
import faiss
print(faiss.__version__)
import numpy as np

# 假设你有 n 个图像向量，每个维度 d=512
# image_vectors = np.stack([img_vec.detach().numpy() for img_vec in data_vector]).astype('float32')

d = data_vector.shape[1]
print(d)
index = faiss.IndexFlatL2(d)  # L2 距离
index2 = faiss.IndexHNSWFlat(d, 32)  # HNSW 索引，32 是 M 参数
index.add(data_vector)
index2.add(data_vector)

1.8.0
200


In [22]:
query_vector = read_fbin(query_path)
print(type(query_vector))
print(query_vector.ndim, query_vector.shape, query_vector.dtype, query_vector.size)
print(query_vector[0])  # Print first 3 elements to verify content

<class 'numpy.ndarray'>
2 (100000, 200) float32 20000000
[ 1.87566467e-02  8.94555729e-03 -2.10110843e-02  1.20234815e-02
 -1.64501518e-02  3.00673805e-02 -5.14313299e-03  9.50199738e-02
 -6.08089333e-03 -6.35381192e-02 -1.08491473e-01  1.16335444e-01
 -1.63473383e-01  1.86934043e-02  6.59038126e-02 -5.81584126e-03
  5.50515726e-02 -8.01400617e-02 -3.43318768e-02  3.14618386e-02
  5.16999178e-02 -1.03157766e-01 -6.99232100e-03 -8.46835822e-02
  4.97051552e-02 -1.12384332e-04 -4.17891033e-02 -1.09427264e-02
  7.66309872e-02 -5.25887199e-02  1.09053455e-01  2.10171994e-02
 -3.82787809e-02  1.41289771e-01 -1.89101938e-02 -4.07587551e-02
  1.02657385e-01  6.38149753e-02  2.78893439e-03  1.48869425e-01
 -7.21347779e-02  6.41020462e-02  1.17272370e-01  1.50459066e-01
  8.25533122e-02 -6.16189539e-02  7.49640958e-03 -1.38607696e-01
  1.06604278e-01 -1.68986112e-01 -9.65005532e-03  4.70842086e-02
 -1.49711713e-01  2.35140440e-03  1.04020555e-02 -5.14691602e-03
 -4.78377305e-02 -4.26866449e-02 

In [24]:
ground_truth_vector = read_ibin(ground_truth_path)
print(type(ground_truth_vector))
print(ground_truth_vector.ndim, ground_truth_vector.shape, ground_truth_vector.dtype, ground_truth_vector.size)
print(ground_truth_vector[0])  # Print first 3 elements to verify content

<class 'numpy.ndarray'>
2 (100000, 100) int32 10000000
[625224632 918264354 348934839 268103431 963214898 625192438 381640478
 818912212 767060891 839249955 723700370 203793603 517287680 182454598
  22901287  26255962 448627860 611319286 182388738 560259494 581832051
 704680499 664306862 906695522 103059900 382900426 251745068 658629309
 366994333 453993764 958270008 686188482 402651086 685676372 178406405
 225953587 994565914  14870335 928362883 359397234 293518009 515858072
 428630604 149632066 883338186 747727309 837553640 865102015 999608238
 683773829 399633393  59367179 634420582  28803698 641378758 431075501
 152884279 512847583 692400751  73193995 211731568 622269134 529445730
 648915194 567177385 548315942 342678485 679253167 536203106 211440296
  67696167   8579576 618619591 985378299 949073667  37256524 591687436
 880504009 423465132 209269713  95754236 960065714 159534122 815402363
 332796344 982592936 454254850 342577218  82894586  17337021  72234841
 539422791 620980104 8

In [25]:
D, I = index.search(query_vector[:10], k=10)

In [26]:
print("Distances:\n", D)

Distances:
 [[0.89707863 0.9164013  0.9188357  0.91929406 0.9199156  0.9214165
  0.9300371  0.93299675 0.9357912  0.9370177 ]
 [1.0761145  1.0771319  1.0795116  1.0896811  1.099861   1.1011736
  1.1015382  1.102242   1.1023581  1.1050858 ]
 [0.84206176 0.8949939  0.929335   0.934093   0.94678354 0.97803175
  0.99529505 0.9966688  1.0000017  1.0004909 ]
 [0.79627216 0.79828155 0.8034636  0.81750876 0.82543755 0.8278471
  0.8359965  0.83786166 0.85278416 0.8532449 ]
 [1.0610423  1.0740168  1.0795767  1.0821952  1.0846894  1.0878892
  1.0878985  1.0910878  1.0911804  1.0937788 ]
 [0.9540234  0.98865676 0.9903217  0.99315965 0.99412787 0.9994553
  1.0027454  1.0028187  1.011336   1.0127182 ]
 [0.86558884 0.90041184 0.91475487 0.9304575  0.9440644  0.9453813
  0.9680559  0.9741669  0.97929835 0.98312163]
 [0.9292965  0.9499552  0.9525008  0.9548248  0.95980585 0.9642168
  0.965322   0.97245014 0.97772807 0.97793216]
 [1.0179996  1.02169    1.0293922  1.0332875  1.0435957  1.0453393
  1.0480

In [27]:
print("Indices:\n", I)

Indices:
 [[433766 728540 851734 310042 861901 561154 940998 648776  57939 471427]
 [143298 927126 922798 910350 893808 857737 215693 650577 397023 868938]
 [700808 541027   9487 574210 164111  22770 873158 455425 463644 707403]
 [555980 515664 717039  85354  51193 856955   5627  74785 929339 495621]
 [596106 422530 250167 519531  95677 107377 121113 799392 362221 323887]
 [633628 405696 750275 257483 803023  70306 149504 403201 167495  76054]
 [202646 787724 341850 133222   6827 523912 620381   7180 889122 903275]
 [336357 222851 362397 434472 787624 633408  58269 296786 376311 653139]
 [988033 819917 827920 666957 806279 700404 812912 749848 856433 605192]
 [351378  57116 861315 249204  81504 432511 941011 799840  73450 173060]]


In [28]:
# index2 = faiss.IndexHNSWFlat(d, 32)  # HNSW 索引，32 是 M 参数
# index2.add(data_vector)
D, I = index2.search(query_vector[:10], k=10)
print("Distances (HNSW):\n", D)


Distances (HNSW):
 [[0.89707863 0.9164013  0.9188357  0.91929406 0.9199156  0.9214165
  0.9300371  0.93299675 0.9357912  0.9370177 ]
 [1.1055816  1.1087906  1.1107972  1.1232569  1.1291201  1.1338917
  1.1351154  1.1355814  1.1361134  1.1402447 ]
 [0.84206176 0.8949939  0.929335   0.94678354 0.97803175 0.99529505
  1.0000017  1.0004909  1.0033789  1.0105431 ]
 [0.79627216 0.79828155 0.8034636  0.81750876 0.82543755 0.8278471
  0.8359965  0.83786166 0.85278416 0.8532449 ]
 [1.0740168  1.0878985  1.0911804  1.0937788  1.0981815  1.1003982
  1.1018034  1.1024446  1.1048635  1.1058141 ]
 [0.9540234  0.9903217  0.99315965 0.99412787 0.9994553  1.0027454
  1.0028187  1.011336   1.0140963  1.0152369 ]
 [0.86558884 0.90041184 0.91475487 0.9304575  0.9440644  0.9453813
  0.9680559  0.9741669  0.97929835 0.98312163]
 [0.9292965  0.9525008  0.95980585 0.9642168  0.965322   0.97245014
  0.97772807 0.97793216 0.98395276 0.9872161 ]
 [1.0293922  1.0332875  1.0435957  1.0494367  1.0502919  1.0521967


In [29]:
print("Indices (HNSW):\n", I)

Indices (HNSW):
 [[433766 728540 851734 310042 861901 561154 940998 648776  57939 471427]
 [935352 451650 401154 828765 656831 505199 309200 370722 997494 316090]
 [700808 541027   9487 164111  22770 873158 463644 707403 505316 226414]
 [555980 515664 717039  85354  51193 856955   5627  74785 929339 495621]
 [422530 121113 362221 323887 448914 329292 945953 236052 411500 945480]
 [633628 750275 257483 803023  70306 149504 403201 167495 253938 850986]
 [202646 787724 341850 133222   6827 523912 620381   7180 889122 903275]
 [336357 362397 787624 633408  58269 296786 376311 653139  44770 816878]
 [827920 666957 806279 856433 605192 361624 926451  61882 895939 544001]
 [ 57116 861315 249204  81504 941011  73450 173060 395096 375934 677335]]


In [30]:
print(ground_truth_vector[1])

[866554089 605877290 838442362 488119882 568179926 297365039 814290707
 568169752 909320134 409471328 966051616 749365818 221720763 984916949
 118964230 167300341 186284176 321529363 422140272 860550809 964598800
 143404192 275782369 595979127 664982983 100427135 729903787 889070901
 426310559 482283752 719074406 563295790 330264223  46874099 386745933
 207331089 348459306  42478173 417683731 990953515 991944347 876176108
 708155914 187710710 874801184  51814217  49374298 711102509 534677561
 751294759 122143620 512667311 396727902 774479427 998504378 625423584
 489098262 802679950 478687408 625384861 780745940 448266271 940784052
 914310858 833860393 415453390 300503259 165650033 388357967 932801677
 278753644 421127702 660723752 738181790  23555098 296853201 764929267
 623793665 406489495 533904862 880031788 858505578 409832119 603630539
 951196187 414078497 151068225 626847097 616539618 455141538 771545745
 895866677 756385106 351436231 251974154 163270134 435345221 378562203
 98472